server:
  port: 8001
  servlet:
    context-path: /api/v1
  # file upload config
  max-file-size: 10MB
  max-request-size: 10MB
  
spring:
  application:
    name: image-upload-cloudinary

  # db config
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: sa

  # jpa config
  jpa:
    hibernate:
      ddl-auto: update

  # h2 config
  h2:
    console:
      enabled: true
      path: /h2-console

# cloudinary config
app:
  cloudinary:
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
    cloud-name: ${CLOUDINARY_CLOUD_NAME}



